components:
  schemas:
    backend:
      description: the backend is...
      properties:
        host:
          description: The host is
          type: integer
        port:
          description: Port of where host is listening
          type: integer
        type:
          description: Currently ELB or empty
          enum:
          - ""
          - ELB
          type: string
      required:
      - host
      - port
      - type
      type: object
    cache:
      properties:
        mode:
          enum:
          - pass
          - static
          type: string
      required:
      - mode
      type: object
    fallback:
      properties:
        mode:
          enum:
          - static
          - dynamic
          type: string
        status:
          type: integer
      required:
      - mode
      - status
      type: object
    rules:
      properties:
        cache:
          $ref: '#/components/schemas/cache'
        fallback:
          $ref: '#/components/schemas/fallback'
          type: object
        method:
          enum:
          - GET
          - PUT
          - POST
          - OPTIONS
          type: string
        name:
          type: string
        path_regex:
          type: string
      required:
      - name
      - path_regex
      - method
      - cache
      type: object
    service:
      properties:
        backend:
          $ref: '#/components/schemas/backend'
          type: object
        hostname_reg:
          type: string
        name:
          pattern: ^[a-z]+$
          type: string
        rules:
          items:
            $ref: '#/components/schemas/rules'
            type: object
          type: array
      required:
      - name
      - hostname_reg
      - backend
      - rules
      type: object
info:
  title: Generated by cue.
  version: no version
openapi: 3.0.0
paths: {}
