components:
  schemas:
    Backend_type:
      properties:
        host:
          type: integer
        port:
          type: integer
        type:
          type: string
      required:
      - host
      - port
      - type
      type: object
    Cache_type:
      properties:
        mode:
          description: |-
            @Summary this is a short summary
            The rest of the comment block is the description
            blah blah1
          enum:
          - pass
          - static
          type: string
      required:
      - mode
      type: object
    Fallback_type:
      properties:
        mode:
          enum:
          - static
          - dynamic
          type: string
        status:
          type: integer
      required:
      - mode
      - status
      type: object
    Rules_type:
      properties:
        cache:
          $ref: '#/components/schemas/Cache_type'
        fallback:
          $ref: '#/components/schemas/Fallback_type'
          type: object
        method:
          enum:
          - GET
          - PUT
          - POST
          - OPTIONS
          type: string
        name:
          type: string
        path_regex:
          type: string
      required:
      - name
      - path_regex
      - method
      - cache
      type: object
    service:
      properties:
        backend:
          $ref: '#/components/schemas/Backend_type'
          type: object
        hostname_reg:
          type: string
        name:
          pattern: ^[a-z]+$
          type: string
        rules:
          items:
            $ref: '#/components/schemas/Rules_type'
            type: object
          type: array
      required:
      - name
      - hostname_reg
      - backend
      - rules
      type: object
info:
  title: Generated by cue.
  version: no version
openapi: 3.0.0
paths: {}
